name: Issue check
on: [push]
jobs:
  triage_issues:
    name: Issue triage
    runs-on: ubuntu-latest
    steps:
      - name: Find old issues and mark them stale
        uses: krizzu/issue-triage-action@master
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          staleAfter: 1
          closeAfter: 3
          staleLabel: "STALE 📺"
          showLogs: true
